#[======================================================================]
#Lightsabers attack damage percentage
#By default, the lightsaber damage is 15, but you can vary the damage by decreasing or increasing the damage percentage from 0.1 to 5.0, that is, from 10% to 500%.
#[======================================================================]
#Range: 0.1 ~ 5.0
lightsaberDamagePercentage = 1.0
#[======================================================================]
#Enable Kyber crystal generation (default: true)
#[======================================================================]
generateKyberCrystal = true
#[======================================================================]
#Force push activation distance
#[======================================================================]
#Range: 1 ~ 50
forcePushDistance = 6
#[======================================================================]
#Force pull activation distance
#[======================================================================]
#Range: 1 ~ 50
forcePullDistance = 8
#[======================================================================]
#Chance to disarm the target when pulling it with force
#[======================================================================]
#Range: 0.0 ~ 1.0
disarmChance = 0.25
#[======================================================================]
#Force grab activation distance
#[======================================================================]
#Range: 1 ~ 50
forceGrabDistance = 8
#[======================================================================]
#Dark side improvement
#Pillagers no longer attack players with the dark effect 'Force Adept'
#[======================================================================]
friendlyPillagers = true
#[======================================================================]
#Enable developer mode (default: false)
#[======================================================================]
devMode = false

