#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 05 19:49:43 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
